/*
 * RLBot Twitch Broker
 * Allows custom Rocket League bots to register themselves with a central broker.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rlbotofficial@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.rlbot.twitch.action.server.invoker.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
