# coding: utf-8

"""
    RLBot Twitch Broker

    Allows custom Rocket League bots to register themselves with a central broker.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: rlbotofficial@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rlbot_twitch_broker_client
from api.chat_api import ChatApi  # noqa: E501
from rlbot_twitch_broker_client.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = api.chat_api.ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_send_chat(self):
        """Test case for send_chat

        """
        pass


if __name__ == '__main__':
    unittest.main()
