# coding: utf-8

"""
    RLBot Twitch Broker

    Allows custom Rocket League bots to register themselves with a central broker.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: rlbotofficial@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rlbot_twitch_broker_client
from api.static_api import StaticApi  # noqa: E501
from rlbot_twitch_broker_client.rest import ApiException


class TestStaticApi(unittest.TestCase):
    """StaticApi unit test stubs"""

    def setUp(self):
        self.api = api.static_api.StaticApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_static_filename_get(self):
        """Test case for static_filename_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
