/*
 * RLBot Twitch Broker
 * Allows custom Rocket League bots to register themselves with a central broker.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rlbotofficial@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.rlbot.twitch.action.server.api;

import org.rlbot.twitch.action.server.invoker.ApiException;
import org.rlbot.twitch.action.server.model.ModelApiResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChatApi
 */
@Ignore
public class ChatApiTest {

    private final ChatApi api = new ChatApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendChatTest() throws ApiException {
        String username = null;
        String message = null;
        ModelApiResponse response = api.sendChat(username, message);

        // TODO: test validations
    }
}
