# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rlbot_twitch_broker_server.models.base_model_ import Model
from rlbot_twitch_broker_server import util


class ActionServerRegistration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """ActionServerRegistration - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ActionServerRegistration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ActionServerRegistration of this ActionServerRegistration.  # noqa: E501
        :rtype: ActionServerRegistration
        """
        return util.deserialize_model(dikt, cls)
