# coding: utf-8

"""
    Bot Action Server

    Allows custom Rocket League bots to accept tactical suggestions in the middle of a game.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: rlbotofficial@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rlbot_action_client
from api.action_api import ActionApi  # noqa: E501
from rlbot_action_client.rest import ApiException


class TestActionApi(unittest.TestCase):
    """ActionApi unit test stubs"""

    def setUp(self):
        self.api = api.action_api.ActionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_choose_action(self):
        """Test case for choose_action

        """
        pass

    def test_get_actions_currently_available(self):
        """Test case for get_actions_currently_available

        """
        pass


if __name__ == '__main__':
    unittest.main()
