# coding: utf-8

"""
    Bot Action Server

    Allows custom Rocket League bots to accept tactical suggestions in the middle of a game.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: rlbotofficial@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rlbot_action_client
from models.available_actions import AvailableActions  # noqa: E501
from rlbot_action_client.rest import ApiException


class TestAvailableActions(unittest.TestCase):
    """AvailableActions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableActions(self):
        """Test AvailableActions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rlbot_action_client.models.available_actions.AvailableActions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
