# coding: utf-8

"""
    RLBot Twitch Broker

    Allows custom Rocket League bots to register themselves with a central broker.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: rlbotofficial@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rlbot_twitch_broker_client
from models.chat_line import ChatLine  # noqa: E501
from rlbot_twitch_broker_client.rest import ApiException


class TestChatLine(unittest.TestCase):
    """ChatLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatLine(self):
        """Test ChatLine"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rlbot_twitch_broker_client.models.chat_line.ChatLine()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
